app_id: "946edd7c-fd06-4f7d-b5bf-80fe4e68adc8"
app_secret: "06.v~po_Cl_6-ldvTXwKI6rjB7gyc1tn.1"
redirect: "https://ddstore.springgo.io:6228/accounts/callback"
# redirect: "https://192.168.200.11:6228/accounts/callback"

scopes: "openid profile offline_access user.read calendars.read"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"