# Generated by Django 3.0.7 on 2021-01-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtgdatamodel',
            name='datetimes',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
