# Generated by Django 3.0.7 on 2021-01-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_dtgdatamodel_oplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='legend',
            name='filesize',
            field=models.IntegerField(default=0),
        ),
    ]
