# Generated by Django 3.0.7 on 2021-01-22 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0008_legend_filesize'),
    ]

    operations = [
        migrations.AddField(
            model_name='legend',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car', related_query_name='cardata', to='interface.CarDataModel'),
        ),
    ]
