# Generated by Django 3.0.7 on 2021-01-22 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0009_legend_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legend',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car', related_query_name='car', to='interface.CarDataModel'),
        ),
    ]
