# Generated by Django 3.0.7 on 2021-01-22 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0010_auto_20210122_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legend',
            name='cardata',
        ),
    ]
