# Generated by Django 3.0.7 on 2021-01-28 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0011_remove_legend_cardata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 11, 12, 45, 101981), null=True),
        ),
        migrations.AlterField(
            model_name='legend',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 11, 12, 45, 100984)),
        ),
        migrations.AlterField(
            model_name='legend',
            name='datetimes',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 11, 12, 45, 100984)),
        ),
        migrations.AlterField(
            model_name='operationlogmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 11, 12, 45, 100984)),
        ),
        migrations.AlterField(
            model_name='operationlogmodel',
            name='datetimes',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 11, 12, 45, 100984)),
        ),
    ]
