# Generated by Django 3.0.7 on 2021-01-28 04:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0012_auto_20210128_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='legend',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='legend',
            name='datetimes',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='operationlogmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='operationlogmodel',
            name='datetimes',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
