# Generated by Django 3.0.7 on 2021-01-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=15, default=0, max_digits=20)),
                ('lon', models.DecimalField(decimal_places=15, default=0, max_digits=20)),
                ('speed', models.DecimalField(decimal_places=15, default=0, max_digits=20)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'gps_info',
            },
        ),
    ]
