# Generated by Django 3.0.7 on 2021-01-28 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0003_auto_20210114_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gps',
            name='oplog',
        ),
    ]
